#ifndef _SMART_PLATFORM_MODULE_CONFIG_H
#define _SMART_PLATFORM_MODULE_CONFIG_H

#include "boardcfg.h"

#define MODULE_NETWORK_DEV   DEV_AITHINKER_A7_ID
#define MODULE_NETWORK_PWD   DEV_LEDGPIO_ID

#endif