#ifndef _SMART_PLATFORM_MODULE_CONFIG_H
#define _SMART_PLATFORM_MODULE_CONFIG_H

#include "boardcfg.h"

#define MODULE_NETWORK_DEV   DEV_AITHINKER_A7_ID
#define MODULE_NETWORK_PWR
#define MODULE_NETWORK_BLINK
#define MODULE_SYSTEM_BLINK1
#define MODULE_SYSTEM_BLINK2

#endif