#ifndef _SMART_PLATFORM_MODULE_CONFIG_H
#define _SMART_PLATFORM_MODULE_CONFIG_H

#include "boardcfg.h"

#define MODULE_NETWORK_DEV   DEV_GPSCOM_ID
#define MODULE_NETWORK_PWR   DEV_LEDGPIO1_ID
#define MODULE_NETWORK_BLINK DEV_LEDGPIO2_ID
#define MODULE_SYSTEM_BLINK1 DEV_LEDGPIO3_ID
#define MODULE_SYSTEM_BLINK2 DEV_LEDGPIO4_ID

#endif