SET(STM32_PLATFORM_TOP ${CMAKE_CURRENT_LIST_DIR}/..)

IF(CMAKE_HOST_UNIX)
    SET(CMAKE_TOOLCHAIN_FILE ${STM32_PLATFORM_TOP}/cmake/toolchain-arm-none-eabi.cmake)
ENDIF()

INCLUDE(${STM32_PLATFORM_TOP}/cmake/board-config-${STM32_PLATFORM_BOARD_NAME}.cmake)

IF(CMAKE_HOST_UNIX)
    INCLUDE(${STM32_PLATFORM_TOP}/cmake/generic-gcc.cmake)
ENDIF()