IF(STM32_PLATFORM_MCU_SERIES STREQUAL "STM32F4xx")
    SET(FPU_PRESENT 1)
    ADD_DEFINITIONS(-DARM_MATH_CM4)
ELSEIF(STM32_PLATFORM_MCU_SERIES STREQUAL "STM32F3xx")
    SET(FPU_PRESENT 1)
    ADD_DEFINITIONS(-DARM_MATH_CM4)
ELSEIF(STM32_PLATFORM_MCU_SERIES STREQUAL "STM32F2xx")
    ADD_DEFINITIONS(-DARM_MATH_CM3)
ELSEIF(STM32_PLATFORM_MCU_SERIES STREQUAL "STM32F1xx")
    ADD_DEFINITIONS(-DARM_MATH_CM3)
ELSE()
    message(FATAL_ERROR
        "No C compiler for '${CMAKE_SYSTEM_PROCESSOR}'"
        " is supported yet."
    )
ENDIF()

INCLUDE_DIRECTORIES(${STM32_PLATFORM_TOP}/arch/CMSIS/Include)
INCLUDE_DIRECTORIES(${STM32_PLATFORM_TOP}/arch/CMSIS/Device/${STM32_PLATFORM_MCU_SERIES}/Include)
INCLUDE_DIRECTORIES(${STM32_PLATFORM_TOP}/arch/${STM32_PLATFORM_MCU_SERIES}_HAL_Driver/Inc)
INCLUDE_DIRECTORIES(${STM32_PLATFORM_TOP}/board/${STM32_PLATFORM_BOARD_NAME}/Include)

AUX_SOURCE_DIRECTORY(${STM32_PLATFORM_TOP}/arch/${STM32_PLATFORM_MCU_SERIES}_HAL_Driver/Src SRC_LIST)
AUX_SOURCE_DIRECTORY(${STM32_PLATFORM_TOP}/arch/CMSIS/Device/${STM32_PLATFORM_MCU_SERIES}/Source SRC_LIST)
AUX_SOURCE_DIRECTORY(${STM32_PLATFORM_TOP}/board/${STM32_PLATFORM_BOARD_NAME}/Source SRC_LIST)

IF(FPU_PRESENT EQUAL 1)

    ADD_DEFINITIONS(-D__FPU_PRESENT=1)

    AUX_SOURCE_DIRECTORY(${STM32_PLATFORM_TOP}/arch/CMSIS/DSP_Lib/BasicMathFunctions SRC_LIST)
    AUX_SOURCE_DIRECTORY(${STM32_PLATFORM_TOP}/arch/CMSIS/DSP_Lib/ComplexMathFunctions SRC_LIST)
    AUX_SOURCE_DIRECTORY(${STM32_PLATFORM_TOP}/arch/CMSIS/DSP_Lib/FastMathFunctions SRC_LIST)
    AUX_SOURCE_DIRECTORY(${STM32_PLATFORM_TOP}/arch/CMSIS/DSP_Lib/MatrixFunctions SRC_LIST)
    AUX_SOURCE_DIRECTORY(${STM32_PLATFORM_TOP}/arch/CMSIS/DSP_Lib/SupportFunctions SRC_LIST)
    AUX_SOURCE_DIRECTORY(${STM32_PLATFORM_TOP}/arch/CMSIS/DSP_Lib/CommonTables SRC_LIST)
    AUX_SOURCE_DIRECTORY(${STM32_PLATFORM_TOP}/arch/CMSIS/DSP_Lib/ControllerFunctions SRC_LIST)
    AUX_SOURCE_DIRECTORY(${STM32_PLATFORM_TOP}/arch/CMSIS/DSP_Lib/FilteringFunctions SRC_LIST)
    AUX_SOURCE_DIRECTORY(${STM32_PLATFORM_TOP}/arch/CMSIS/DSP_Lib/StatisticsFunctions SRC_LIST)
    AUX_SOURCE_DIRECTORY(${STM32_PLATFORM_TOP}/arch/CMSIS/DSP_Lib/TransformFunctions SRC_LIST)

ENDIF()

SET_PROPERTY(SOURCE ${STM32_PLATFORM_TOP}/arch/CMSIS/Device/${STM32_PLATFORM_MCU_SERIES}/Source/startup_${STM32_PLATFORM_MCU_TYPE}.s PROPERTY LANGUAGE C)
LIST(APPEND SRC_LIST ${STM32_PLATFORM_TOP}/arch/CMSIS/Device/${STM32_PLATFORM_MCU_SERIES}/Source/startup_${STM32_PLATFORM_MCU_TYPE}.s)