INCLUDE_DIRECTORIES(${SMART_PLATFORM_TOP}/platform/lwip/Include)
INCLUDE_DIRECTORIES(${SMART_PLATFORM_TOP}/lwip/src/include)

AUX_SOURCE_DIRECTORY(${SMART_PLATFORM_TOP}/platform/lwip/Source SRC_LIST)

AUX_SOURCE_DIRECTORY(${SMART_PLATFORM_TOP}/lwip/src/netif/ppp SRC_LIST)
AUX_SOURCE_DIRECTORY(${SMART_PLATFORM_TOP}/lwip/src/netif/ppp/polarssl SRC_LIST)
AUX_SOURCE_DIRECTORY(${SMART_PLATFORM_TOP}/lwip/src/core SRC_LIST)
AUX_SOURCE_DIRECTORY(${SMART_PLATFORM_TOP}/lwip/src/core/ipv4 SRC_LIST)
AUX_SOURCE_DIRECTORY(${SMART_PLATFORM_TOP}/lwip/src/core/ipv6 SRC_LIST)
AUX_SOURCE_DIRECTORY(${SMART_PLATFORM_TOP}/lwip/src/api SRC_LIST)

ADD_DEFINITIONS(-DNDEBUG)