#ifndef _SMART_PLATFORM_BOARDCFG_H
#define _SMART_PLATFORM_BOARDCFG_H

#define DEV_GPSCOM_ID   3
#define DEV_LEDGPIO1_ID 4
#define DEV_LEDGPIO2_ID 5
#define DEV_LEDGPIO3_ID 6
#define DEV_LEDGPIO4_ID 7

#endif